-- Prueba abecedario.
insert into test values(1,"Prueba del abecedario",1,"¡Deletrea algunas palabras!");
insert into t_p values(1,1);
insert into t_p values(1,2);
insert into t_p values(1,3);
insert into t_p values(1,4);
insert into t_p values(1,5);
insert into pregunta values(1,'¿Como deletrarías la palabra "hola"?');
insert into respuesta values(null,1,47,1);
insert into respuesta values(null,1,54,2);
insert into respuesta values(null,1,51,3);
insert into respuesta values(null,1,40,4);
insert into pregunta values(2,'¿Como deletrarías la palabra "jaime"?');
insert into respuesta values(null,2,49,1);
insert into respuesta values(null,2,40,2);
insert into respuesta values(null,2,48,3);
insert into respuesta values(null,2,52,4);
insert into respuesta values(null,2,44,5);
insert into pregunta values(3,'¿Como deletrarías la palabra "montaña"?');
insert into respuesta values(null,3,52,1);
insert into respuesta values(null,3,54,2);
insert into respuesta values(null,3,53,3);
insert into respuesta values(null,3,59,4);
insert into respuesta values(null,3,40,5);
insert into respuesta values(null,3,66,6);
insert into respuesta values(null,3,40,7);
insert into pregunta values(4,'¿Como deletrarías la palabra "casa"?');
insert into respuesta values(null,4,42,1);
insert into respuesta values(null,4,40,2);
insert into respuesta values(null,4,58,3);
insert into respuesta values(null,4,40,4);
insert into pregunta values(5,'¿Como deletrarías la palabra "zanahoria"?');
insert into respuesta values(null,5,65,1);
insert into respuesta values(null,5,40,2);
insert into respuesta values(null,5,53,3);
insert into respuesta values(null,5,40,4);
insert into respuesta values(null,5,47,5);
insert into respuesta values(null,5,54,6);
insert into respuesta values(null,5,57,7);
insert into respuesta values(null,5,48,8);
insert into respuesta values(null,5,40,9);